export const ErrorCode = {
	INVALID_POSITION_ID: "INVALID_POSITION_ID",
	INVALID_SUB_POSITION_ID: "INVALID_SUB_POSITION_ID",
	TRANSACTION_NOT_PERMITTED: "TRANSACTION_NOT_PERMITTED",
	PRICE_LARGER_THAN_BUYING_POWER: "PRICE_LARGER_THAN_BUYING_POWER",
	CLIENT_ID_NOT_FOUND: "CLIENT_ID_NOT_FOUND",
	CLIENT_EMAIL_NOT_FOUND: "CLIENT_EMAIL_NOT_FOUND",
	INVALID_BIRTHDATE: "INVALID_BIRTHDATE",
	INVALID_EMAIL: "INVALID_EMAIL",
	INVALID_PLZ: "INVALID_PLZ",
	INVALID_POSITION_ID_OR_POSITION_SUB_ID:
		"INVALID_POSITION_ID_OR_POSITION_SUB_ID",
	CLIENT_HAS_NO_DEPOTS: "CLIENT_HAS_NO_DEPOTS",
	PRICE_LARGER_THAN_BALANCE_AMT: "PRICE_LARGER_THAN_BALANCE_AMT",
};
